# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.20
jobs:
  build:
    docker: 
      - image: circleci/node:13.8.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: zip -r project1.zip project1
