version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:13.8.0 # the primary container, where your job's commands are run
    orbs:
      - aws-cli: circleci/aws-cli@0.1.20
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: zip -r project1.zip project1
