# This code is licensed from CircleCI to the user under the MIT license. See
# https://circleci.com/orbs/registry/licensing for details.
version: 2.1

description: |
  Install and configure the AWS command-line interface (awscli).

display:
  home_url: https://github.com/CircleCI-Public/aws-cli-orb

executors:
  default:
    description: |
      The Debian-based Docker container to use when
      installing/configuring the AWS CLI

    parameters:
      python-version:
        type: string
        default: "2.7"

      debian-release:
        type: string
        default: "stretch"

    docker:
      - image: circleci/python:<<parameters.python-version>>-<<parameters.debian-release>>

commands:
  install:
    description: "Install the AWS CLI via Pip if not already installed."
    parameters:
      skip-install-check:
        description: |
          Set to true to skip checking for existing installations before installing.
        type: boolean
        default: false
    steps:
      - run:
          name: "Install AWS CLI"
          command: |
            if [ "<<parameters.skip-install-check>>" == "false" ] && which aws > /dev/null; then
              echo "The AWS CLI is already installed. Skipping."
              exit 0
            fi

            export PIP=$(which pip pip3 | head -1)
            if [[ -n $PIP ]]; then
              if which sudo > /dev/null; then
                sudo $PIP install awscli --upgrade
              else
                # This installs the AWS CLI to ~/.local/bin. Make sure that ~/.local/bin is in your $PATH.
                $PIP install awscli --upgrade --user
              fi
            elif [[ $(which unzip curl | wc -l) -eq 2 ]]; then
              cd
              curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
              unzip awscli-bundle.zip
              if which sudo > /dev/null; then
                sudo ~/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
              else
                # This installs the AWS CLI to the default location (~/.local/lib/aws) and create a symbolic link (symlink) at ~/bin/aws. Make sure that ~/bin is in your $PATH.
                awscli-bundle/install -b ~/bin/aws
              fi
              rm -rf awscli-bundle*
              cd -
            else
              echo "Unable to install AWS CLI. Please install pip."
              exit 1
            fi

  setup:
    description: |
      Configure and store AWS credentials in
      ~/.aws/credentials and ~/.aws/config

    parameters:
      profile-name:
        description: Profile name to be configured.
        type: string
        default: "default"

      aws-access-key-id:
        description: |
          AWS access key id for IAM role. Set this to the name of
          the environment variable you will use to hold this
          value, i.e. AWS_ACCESS_KEY.
        type: env_var_name
        default: AWS_ACCESS_KEY_ID

      aws-secret-access-key:
        description: |
          AWS secret key for IAM role. Set this to the name of
          the environment variable you will use to hold this
          value, i.e. $AWS_SECRET_ACCESS_KEY.
        type: env_var_name
        default: AWS_SECRET_ACCESS_KEY

      aws-region:
        description: |
          Env var of AWS region to operate in
          (defaults to AWS_DEFAULT_REGION)
        type: env_var_name
        default: AWS_DEFAULT_REGION

      configure-default-region:
        description: |
          Some AWS actions don't require a region; set this to false if you do not want to store a default region in ~/.aws/config
        type: boolean
        default: true

      skip-install-check:
        description: |
          Set to true to skip checking for existing installations before installing.
        type: boolean
        default: false

    steps:
      - install:
          skip-install-check: <<parameters.skip-install-check>>

      - run:
          name: Configure AWS Access Key ID
          command: |
            aws configure set aws_access_key_id \
            $<<parameters.aws-access-key-id>> \
            --profile <<parameters.profile-name>>

      - run:
          name: Configure AWS Secret Access Key
          command: |
            aws configure set aws_secret_access_key \
            $<<parameters.aws-secret-access-key>> \
            --profile <<parameters.profile-name>>

      - when:
          condition: <<parameters.configure-default-region>>
          steps:
            - run:
                name: Configure AWS default region
                command: |
                  aws configure set region $<<parameters.aws-region>> \
                  --profile <<parameters.profile-name>>

examples:
  install_aws_cli:
    description: Easily install and configure the AWS CLI automatically in your jobs or commands.
    usage:
        version: 2.1

        orbs:
          aws-cli: circleci/aws-cli@x.y

        jobs:
          aws-cli-example:
            executor: aws-cli/default
            steps:
              - checkout
              - aws-cli/setup:
                  profile-name: example
              - run: echo "Run your code here"

        workflows:
          version: 2
          aws-cli:
            jobs:
              - aws-cli-example:
                  context: aws
